spring.application.name=DP_BackEnd

app.debug = false


#####################      SSL / HTTPS  #####################################
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=8Of3ez4QM3TkaV3UcZp
server.ssl.key-alias=springboot

logging.level.org.springframework.boot.web.embedded.tomcat=DEBUG
logging.level.org.springframework.boot.web.server=DEBUG

######################      SERVER - SMPT   ###############################
spring.mail.host=mail.tophost.it
spring.mail.port=587
spring.mail.username=vbgio.net30489
spring.mail.password=wH6BEwr5Ht

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000on

app.mailHtml = false

######################      DATABASE  -  postgresql   ###############################
spring.datasource.username=postgres
spring.datasource.password=e+U!GK&ijc1gzXNb9-r!&jOFG?o!0q
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
  # create-drop
# old value update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG


######################      DISCOR  -  Config   ###############################
# --- OAuth2 Client: Discord (registration) ---
spring.security.oauth2.client.registration.discord.scope=identify,email
spring.security.oauth2.client.registration.discord.client-name=Discord
spring.security.oauth2.client.registration.discord.authorization-grant-type=authorization_code

# -- Codici Ufficiali
spring.security.oauth2.client.registration.discord.client-id=1451281373926260778
spring.security.oauth2.client.registration.discord.client-secret=UN-gmufAc7YsIcvCYW-cbjyE1UYGNfMX

discord.bot.token=${DISCORD_BOT_TOKEN}
discord.client.id=${DISCORD_CLIENT_ID}
discord.client.secret=${DISCORD_CLIENT_SECRET}
discord.guild.id=${DISCORD_GUILD_ID}

discord.admin-role-id = 1366783113224523850
discord.member-role-id=1451276817179873454


# --- OAuth2 Provider endpoints: Discord ---
spring.security.oauth2.client.provider.discord.authorization-uri=https://discord.com/api/oauth2/authorize
spring.security.oauth2.client.provider.discord.token-uri=https://discord.com/api/oauth2/token
spring.security.oauth2.client.provider.discord.user-info-uri=https://discord.com/api/users/@me
spring.security.oauth2.client.provider.discord.user-name-attribute=id

server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=None

###########################     UPLOAD FILE     ############################

# (eine) File Upload Max Siez - PHP : max_file_uploads
spring.servlet.multipart.max-file-size=20MB

# Request POST Max Siez  (zb. max 3 file a 10 MB) - PHP :  post_max_size
spring.servlet.multipart.max-request-size=60MB