###########################################################
##########      SETTING IN PROD (OnLine)       ############
###########################################################

#server.ssl.key-store=file:/app/keystore.p12
server.ssl.key-store=classpath:keystore.p12
spring.datasource.url=jdbc:postgresql://dp_postgres:5433/postgres
spring.security.oauth2.client.registration.discord.redirect-uri=https://93.186.254.85:8443/api/auth/discord/callback
discord.redirect-uri=https://93.186.254.85:8443/api/auth/discord/callback
logging.level.at.spengergasse.dp_backend.* = warn

frontend.base-url = https://93.186.254.85:8443

#Port fur Proxy
server.port=7443

### Dir Upload File  ####
app.upload-dir=/app/uploads
